Get the GitHub details from git itself

diff --git a/watson b/watson
--- a/watson
+++ b/watson
@@ -28,8 +28,39 @@
 
 dryRun=false
 
+# Get the GitHub details from git itself.
+gitRemote=($(git remote -v))
+gitUrl=${gitRemote[1]}
+
+# This regular expression extracts the organisation
+# and app from a GitHub remote URL (works on both SSH
+# and HTTPS URLs.)
+gitUrlRegExp='.*?github\.com.(.*?)/(.*?)\.git'
+
+# Execute the regular expression.
+[[ $gitUrl =~ $gitUrlRegExp ]]
+
+# Get the GitHub organisation and app name from the
+# regular expression results.
+github_organisation_original="${BASH_REMATCH[1]}"
+github_app_original="${BASH_REMATCH[2]}"
+
+running_on_working_copy_of_original_repository=$([[ "${github_organisation_original}" == "small-tech" && "${github_app_original}" == "watson" ]] && echo true || echo false)
+
 function show_help () {
   echo 'Usage: watson [--dryrun|-d|--help|-h]'
+  if [[ ${running_on_working_copy_of_original_repository} == 'true' ]]; then
+    echo ''
+    echo -e "❌ \033[41mERROR\033[0m You currently have the original Watson repository cloned."
+    echo ''
+    echo 'To use Watson:'
+    echo ''
+    echo '1. Go to https://github.com/small-tech/watson'
+    echo '2. Press the green “Use this template” button to create a new repository from Watson.'
+    echo '3. Clone your new repository.'
+    echo '4. Switch to that repository.'
+    echo '5. Run ./watson'
+  fi
   exit
 }
 
@@ -40,11 +71,21 @@ function dry_run () {
   echo "Carries out substitutions, presents diff, reverts changes, and exits."
 }
 
+# Apply flags, if any.
 [[ $1 == '--dry-run' || $1 == '-d' ]] && dry_run
 [[ $1 == '--help' || $1 == '-h' ]] && show_help
 
+# Check that the developer hasn’t accidentally cloned
+# The Watson repository instead of creating their own
+# using the “use this template” button on GitHub to
+# create their own repository based on Watson. If so,
+# warn them and exit.
+if [[ ${running_on_working_copy_of_original_repository} == 'true' ]]; then
+  show_help
+fi
+
 current_step=0
-steps=('GitHub Details' 'App Details (1/2)' 'App Details (2/2)' 'Copyright Details' 'Parse responses' 'Perform substitutions' 'Rename files' 'Meson build' 'Create translations' 'Delete self' 'Recreate git repository' 'Exit')
+steps=('App Details (1/2)' 'App Details (2/2)' 'Copyright Details' 'Parse responses' 'Perform substitutions' 'Rename files' 'Meson build' 'Create translations' 'Delete self' 'Recreate git repository' 'Exit')
 
 # Trap errors and handle them gracefully.
 #
@@ -64,13 +105,6 @@ trap 'handle_error ${LINENO} $? ' ERR
 # Constants
 
 readonly copyright_year=$(date '+%Y')
-
-# Github details.
-github_details_pipe_separated=$(zenity --forms --width=300 --title="Watson" --text="\n  <big><u>GitHub details</u></big>  \n\n  <i>https://github.com/<big>‹Organisaton›</big>/<big>‹App›</big></i>\n" --add-entry="Organisation:" --add-entry="App:")
-
-current_step=$(( current_step + 1 ))
-
-echo ${github_details_pipe_separated}
 
 # Get app details (1/2).
 app_details_pipe_separated=$(zenity --forms --height=260 --title="Watson" --text="\n  <big><u>App details (1/2)</u></big>" --add-entry="Name:" --add-entry="Generic Name (e.g., Web Browser):" --add-entry="Description" --add-entry="Tooltip text (comment)" --add-entry="Keywords (separated;by;semicolons)")
@@ -94,7 +128,6 @@ current_step=$(( current_step + 1 ))
 # Parse responses.
 
 # Parse the pipe-separated results returned from the Zenity dialogues into bash arrays.
-IFS='|' read -ra github_details <<< "${github_details_pipe_separated}"
 IFS='|' read -ra app_details <<< "${app_details_pipe_separated}"
 IFS='|' read -ra copyright_details <<< "${copyright_details_pipe_separated}"
 
@@ -103,8 +136,6 @@ IFS='|' read -ra copyright_details <<< "${copyright_details_pipe_separated}"
 # https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s02.html
 #
 # TODO: Also handle edge case of names that begin with numbers? (Prefix with an underscore.)
-github_organisation_original=${github_details[0]}
-github_app_original=${github_details[1]}
 github_organisation=${github_organisation_original//'-'/'_'}
 github_app=${github_app_original//'-'/'_'}
 
